org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false
org.gradle.parallel=true

# Mod Properties
mod.version=build-10
maven_group=me.noramibu
archives_base_name=nora-tweaks

# 26.1.x dependency versions
minecraft_version=26.1.2
loader_version=0.19.2
fabric_api_version=0.146.1+26.1.2
meteor_version=26.1.2
baritone_version=26.1
xpple_cubiomes_version=0.0.0-2026.4.26.1777239026+3ca29459757d2ca5480dc183b22ef8923e2e6318
