org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=true
org.gradle.parallel=true

# Mod Properties
mod.version=build-8
maven_group=me.noramibu
archives_base_name=nora-tweaks

# 1.21.11-only dependency versions
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.2
meteor_version=1.21.11
baritone_version=1.21.11
